version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mail-manager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mail-manager-network

  backend:
    build: ./backend
    container_name: mail-manager-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - DB_NAME=mail_management_db
      - CORS_ORIGINS=*
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_SCOPE=${AZURE_SCOPE}
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    networks:
      - mail-manager-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
        REACT_APP_AZURE_CLIENT_ID: ${REACT_APP_AZURE_CLIENT_ID}
        REACT_APP_AZURE_TENANT_ID: ${REACT_APP_AZURE_TENANT_ID}
        REACT_APP_AZURE_REDIRECT_URI: ${REACT_APP_AZURE_REDIRECT_URI}
        REACT_APP_AZURE_SCOPE: ${REACT_APP_AZURE_SCOPE}
    container_name: mail-manager-frontend
    restart: unless-stopped
    ports:
      - "3333:80"
    depends_on:
      - backend
    networks:
      - mail-manager-network

networks:
  mail-manager-network:

volumes:
  mongodb_data:
